#!/bin/sh

set -eu

usage() {
  echo "usage: generate_homebrew_formula.sh <tag> <checksums-file> <output-file>" >&2
  exit 2
}

[ "$#" -eq 3 ] || usage

tag=$1
checksums_file=$2
output_file=$3

case "$tag" in
  v[0-9]*) ;;
  *)
    echo "error: tag must start with v followed by a digit: $tag" >&2
    exit 2
    ;;
esac

[ -f "$checksums_file" ] || {
  echo "error: checksums file not found: $checksums_file" >&2
  exit 1
}

checksum_for() {
  filename=$1
  checksum=$(awk -v filename="$filename" '$2 == filename { print $1 }' "$checksums_file")
  if ! printf '%s\n' "$checksum" | grep -Eq '^[0-9a-f]{64}$'; then
    echo "error: missing or invalid checksum for $filename" >&2
    exit 1
  fi
  printf '%s' "$checksum"
}

darwin_amd64=$(checksum_for skm_darwin_amd64.tar.gz)
darwin_arm64=$(checksum_for skm_darwin_arm64.tar.gz)
linux_amd64=$(checksum_for skm_linux_amd64.tar.gz)
linux_arm64=$(checksum_for skm_linux_arm64.tar.gz)
version=${tag#v}

mkdir -p "$(dirname "$output_file")"
cat >"$output_file" <<EOF
# This file is generated by skm's release workflow. DO NOT EDIT.
class Skm < Formula
  desc "Manage and deploy AI Agent Skills"
  homepage "https://github.com/zzzzzyijie/skm"
  version "$version"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/zzzzzyijie/skm/releases/download/v#{version}/skm_darwin_amd64.tar.gz"
      sha256 "$darwin_amd64"
    end
    on_arm do
      url "https://github.com/zzzzzyijie/skm/releases/download/v#{version}/skm_darwin_arm64.tar.gz"
      sha256 "$darwin_arm64"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zzzzzyijie/skm/releases/download/v#{version}/skm_linux_amd64.tar.gz"
      sha256 "$linux_amd64"
    end
    on_arm do
      url "https://github.com/zzzzzyijie/skm/releases/download/v#{version}/skm_linux_arm64.tar.gz"
      sha256 "$linux_arm64"
    end
  end

  def install
    if OS.mac?
      chmod 0755, "skm"
      system "/usr/bin/xattr", "-c", "skm"
    end
    bin.install "skm"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/skm version")
  end
end
EOF
