#!/bin/sh

set -eu

usage() {
  echo "usage: generate_homebrew_cask.sh <tag> <macos-checksums-file> <output-file>" >&2
  exit 2
}

[ "$#" -eq 3 ] || usage

tag=$1
checksums_file=$2
output_file=$3

case "$tag" in
  v[0-9]*) ;;
  *)
    echo "error: tag must start with v followed by a digit: $tag" >&2
    exit 2
    ;;
esac

[ -f "$checksums_file" ] || {
  echo "error: checksums file not found: $checksums_file" >&2
  exit 1
}

version=${tag#v}
dmg="SKM-$version-universal.dmg"
checksum=$(awk -v filename="$dmg" '$2 == filename { print $1 }' "$checksums_file")
if ! printf '%s\n' "$checksum" | grep -Eq '^[0-9a-f]{64}$'; then
  echo "error: missing or invalid checksum for $dmg" >&2
  exit 1
fi

mkdir -p "$(dirname "$output_file")"
cat >"$output_file" <<EOF
# This file is generated by skm's release workflow. DO NOT EDIT.
cask "skm-app" do
  version "$version"
  sha256 "$checksum"

  url "https://github.com/zzzzzyijie/skm/releases/download/v#{version}/SKM-#{version}-universal.dmg"
  name "SKM"
  desc "Native macOS manager for AI Agent Skills"
  homepage "https://github.com/zzzzzyijie/skm"

  depends_on macos: ">= :sonoma"

  app "SKM.app"
end
EOF
